name: GenerateUML

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  generate-uml:
    runs-on: ubuntu-latest
    name: Generate UML.md
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Upload File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ github.workspace }}
          retention-days: 1
      - name: List Workspace Files
        run: |
          # Change to the workspace directory
          cd ${{ github.workspace }}

          # List all files and directories in the workspace
          find .

      - name: Show Contents of Files
        run: |
          # Change to the directory where your files are located
          cd ${{ github.workspace }}/src/main/kotlin/models

          # List the files in the folder
          ls

          # Show the contents of each file in the folder
          for file in *; do
            echo "Contents of $file:"
            cat "$file"
            echo "-------------------------"
          done

      - name: kotlinmaid
        id: generate-UML
        uses: nurzhanme/kotlinmaid-github-action@v0.0.8-alpha
        with:
          entity-path: src/main/kotlin/models
          package-name: kotlinmaid-github-action-sample.models
          uml-file: UML.md
 
      - name: Commit UML.md changes.
        id: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "UML generated"
          git push
        shell: bash
